Fix get_token_info

diff --git a/common b/common
--- a/common
+++ b/common
@@ -5,8 +5,7 @@ function check_error() {
     local error_msg
     error_msg=$(jq ".error")
     if [[ ( -n $error_msg ) && ( $error_msg != null ) ]]; then
-        printf "Error: "
-        echo "$error_msg"
+        printf "Error: %s" "$error_msg" 1>&2 1>/dev/null
         exit 1
     fi
 }
diff --git a/modules/check b/modules/check
--- a/modules/check
+++ b/modules/check
@@ -4,9 +4,12 @@ source $SWEIBO_DIR/common
 
 echo "Checking authorization validation..."
 
-response=$($MODULE_DIR/oauth2/get_token_info)
-if [ -z $response ]; then exit 1; fi
+response=$("$SWEIBO_MODULE_DIR/oauth2/get_token_info")
+if [ -z "$response" ]; then
+    echo -e "\e[31mInvalid authorization\e[0m"
+    exit 1
+fi
 
 user_uid=$(echo $response | jq ".uid")
-printf "\tUID: %s\n" $user_uid
+printf "\tUID: %s\n" "$user_uid"
 echo "Valid authorization"
